### ISSUE TITLE
Remove route hashing

### ISSUE THREAD

**Issue by WickedBrat** [Cynthesize/cynthesize-frontend#192]
Remove route hashing with what has been suggested by Angular using Angular Universal. 
Link: [https://angular.io/guide/universal](https://angular.io/guide/universal)

**Comment by WickedBrat** [comment]
Fixed with following `app.yaml` configuration on GCP:

```
runtime: python27
api_version: 1
threadsafe: true
handlers:
- url: /(.*\.(gif|svg|png|jpg|css|js|ttf|woff2|woff)(|\.map))$
  static_files: dist/\1
  upload: dist/(.*)(|\.map)
- url: /(.*)
  static_files: dist/index.html
  upload: dist/index.html
```
